version: '3.7'

services:

  node:
    container_name: chat-node
    image: pasxin/chat-node
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      dockerfile: ./.docker/node/Dockerfile
      context: ./
    ports:
      - 3002:3002
    depends_on:
      - postgres
      - redis
    networks:
      - paskhin-me

  postgres:
    container_name: chat-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - paskhin-me

  redis:
    container_name: chat-redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache:/data
    networks:
      - paskhin-me

  nginx:
    container_name: chat-nginx
    image: pasxin/chat-nginx
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
      args:
        - HTTP_AUTH_PASSWORD=${HTTP_AUTH_PASSWORD}
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - paskhin-me

volumes:
  pgdata: { }
  cache: { }

networks:
  paskhin-me:
    name: paskhin-me
