version: '3.7'

services:

  node:
    container_name: node
    image: pasxin/chat-node
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      dockerfile: ./.docker/node/Dockerfile
      context: ./
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache:/data

  nginx:
    container_name: nginx
    image: pasxin/chat-nginx
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
      args:
        - HTTP_AUTH_PASSWORD=${HTTP_AUTH_PASSWORD}
    ports:
      - ${CLIENT_PORT}:80

volumes:
  pgdata: {}
  cache: {}
