name: Build check

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build packages
        run: npm run build:prod

      - name: Run eslint and test
        run: npm run check:all
