name: Test

on: [workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'latest'
        
    - name: Install dependencies
      run: npm i
        
    - name: Run eslint and test
      run: npm run check:all
